### ISSUE TITLE
int64 value() turns to Scientific notation

### ISSUE THREAD

**Issue by c625473164** [tidwall/gjson#114]
```
func TestValue(t *testing.T) {
	val := `{"owner_id":106134567558}`
	fmt.Println(gjson.Get(val, "owner_id").Value())
}

go test -timeout 30s -run ^(TestValue)$ -v
=== RUN   TestValue
1.06134567558e+11
--- PASS: TestValue (0.00s)
PASS
ok      git.byted.org/aweme/gopkg/ajson/test    0.006s
```

is there a gjson.UseNumber option to resolve this problem?

**Comment by tidwall** [comment]
I recommend the `Int()` function, which returns the number as an `int64`.

```
fmt.Println(gjson.Get(val, "owner_id").Int())
```

**Comment by c625473164** [comment]
> I recommend the `Int()` function, which returns the number as an `int64`.
> 
> ```
> fmt.Println(gjson.Get(val, "owner_id").Int())
> ```

The case we meet is special. We don't know the actual type(string or int) sometimes so we want to get the `Value()` and then switch type of it.

**Comment by tidwall** [comment]
Perhaps I misunderstood. It appears in your case that the `Value()` function is converting the gjson result into a proper Go type and storing that result in an `interface{}`. 

Here's the conversion table from JSON >> Go:

```
boolean >> bool
number  >> float64
string  >> string
null    >> nil
array   >> []interface{}
object  >> map[string]interface{}
```

The `Value()` call will never return a Go type other than the one above. In your case the number from `{"owner_id":106134567558}` is being converted into a float64. Most JSON parsers, including standard Go and Javascript, default json numbers to floating points.

---- 

The output using the `fmt.Println(gjson.Get(val, "owner_id").Value())` is printing a string representation of the floating point. The way Go handles floating point strings by default is a little weird, but unless you provide a string format using `fmt.Printf`, Go will default the output format to `%v`, which for a floating point is equivalent to `%g`. The `%g` will output as `%e` (scientific notation) for large exponents, otherwise `%f`. 

Thus the number `1.06134567558e+11` is equivalent to `106134567558`.

The Go documentation dives into this in depth on their [`fmt`](https://golang.org/pkg/fmt/#hdr-Printing) page.

**Comment by c625473164** [comment]
Yeah I understand why I see the unexpected results because of the `%v`. Thanks so much.
On this test It print the value that I want
```
func TestValue(t *testing.T) {
	val := `{"owner_id":106134567558}`
	fmt.Printf("%f\n", gjson.Get(val, "owner_id").Value())
}
go test -timeout 30s git.byted.org/aweme/gopkg/ajson/test -run ^(TestValue)$ -v
=== RUN   TestValue
106134567558.000000
--- PASS: TestValue (0.00s)
```

By the way, Golang Encoding json provide us the Usenumber option, witch seems more convinent in my case
```
func TestValueForEncodingJson(t *testing.T) {
	val := []byte(`{"owner_id":106134567558}`)
	var target map[string]interface{}
	d := json.NewDecoder(bytes.NewReader(val))
	d.UseNumber()
	d.Decode(&target)
	fmt.Println(target)
}

go test -timeout 30s git.byted.org/aweme/gopkg/ajson/test -run ^(TestValueForEncodingJson)$ -v
=== RUN   TestValueForEncodingJson
map[owner_id:106134567558]
--- PASS: TestValueForEncodingJson (0.00s)
PASS
ok      git.byted.org/aweme/gopkg/ajson/test    0.006s
```
then I can just convert the string to Int64

**Comment by tidwall** [comment]
I'm glad to hear that you found a solution.

Regarding the `UseNumber()` option (and the resulting [`Number`](https://golang.org/pkg/encoding/json/#Number)) type, this seems really useful for the stdlib json package. Though I'm not sure if it would be a good solution for gjson. Mainly because a `gjson.Result` already has all of the conversation function included, such as `Int()`, `Uint()`, `Bool()`, `Float()`, etc.

I'm closing this issue, but please feel free to reopen if needed.
