### ISSUE TITLE
Why Raw returns string type, not []byte?

### ISSUE THREAD

**Issue by DenisNeustroev** [tidwall/gjson#12]

**Comment by tidwall** [comment]
This is because the base type for `gjson.Get(json, path)` is the string. The `result.Raw` field is just a substring of the originally passed in `json` parameter. From my testing, having everything as strings seems to keep the total allocations down and allows for better overall performance

If you are using the `gjson.GetBytes(json, path)` function and you want to avoid the converting `result.Raw` to a `[]byte`, then you can use this pattern:

```go
var json []byte  // using json byte slice
result := gjson.GetBytes(json, path)
var raw []byte
if result.Index > 0 {
        raw = json[result.Index:result.Index+len(result.Raw)]
} else {
        raw = []byte(result.Raw)
}
```

Which is a best-effort no allocation sub slice of the original json. This method utilizes the `result.Index` field, which is the position of the raw data in the original json. 

It's possible that this value might equal zero, in which case we'll just convert the `result.Raw` to a `[]byte`.

I hope this information helps. Let me know if this does not answer you question.

**Comment by DenisNeustroev** [comment]
Thank you for the detailed answer, this method is very useful, can it be included in the documentation or realized in the code?

**Comment by tidwall** [comment]
Good idea. I think I'll add it to the README file.
