### ISSUE TITLE
Any chance of adding recursive descent support?

### ISSUE THREAD

**Issue by TomAnthony** [tidwall/gjson#130]
As detailed at https://goessner.net/articles/JsonPath/ - recursive descent allows specifying elements without needing to give their whole path.

The syntax clashes with the JSON Lines syntax, but it could be implemented differently.

It is very helpful for deeply nested elements where it is hard to get a whole path; as a simple example:

```json
{ "something": {
    "anything": {
      "abcdefg": {
          "finally": {
            "important": {
                "secret": "password"
            }
        }
      }
    }
  }
}
```

With recursive descent you could do `$..secret` and get `[ "password"]` as the output.

Are there plans, or appetite, to support such a feature?

Thanks!

**Comment by tidwall** [comment]
I have no plans at this time, but I think it's an interesting idea. 

Perhaps using three dots followed by the path.

**Comment by tidwall** [comment]
I'm closing for now, but please reopen if you further ideas.

**Comment by xxxserxxx** [comment]
@tidwall closed, because you aren't interested in implementing it, or closed because you would like more input on how it'd be implemented?

XPath, for XML, has wildcard path support with the `ancestor()` and `descendant()` (a.k.a. `..`) axes.  It's a pain to do in `jq` as well, and is (IME) one of the most *common* operations users would like to do.  There's a lot of JSON with deeply nested schemas, and -- unlike XML -- JSON is expected to be, and frequently is, far less restricted in structure.

A real-life use-case is the Linux window manager, `i3`.  `i3` has a command-line tool called `i3-msg` with which users can dump out a JSON representation of the desktop tree.  Because `i3` supports containers, the tree can be arbitrarily nested, and windows could be 3 levels deep, or 10 levels deep.  A common problem **I** face when writing scripts is how to find the ID of an arbitrary window that has a certain WM NAME attribute.  This is an absurdly difficult problem to solve in `jq`, and without a path wildcard element, it's almost impossible in `jj`.

Support for some sort of wildcard syntax (`*`, `...`, `%` -- almost any commonly used wildcard) would be a great addition.

**Comment by tidwall** [comment]
I just added the `@dig` modifier:

```json
{ "something": {
    "anything": {
      "abcdefg": {
          "finally": {
            "important": {
                "secret": "password"
            }
        }
      }
    }
  }
}
```

```
@dig:secret => ["password"]
```

I hope you find this helpful.
