### ISSUE TITLE
bug: building on wasm fails to index Result correctly

### ISSUE THREAD

**Issue by Kegsay** [tidwall/gjson#157]
I'm a user of `sjson` which allows deleting keys. `sjson` relies on `gjson.Get(json, path string) Result` to pull out the key to delete, as per [this file](https://github.com/tidwall/sjson/blob/c943cc8c8d751d9b33444adf78ae04c2fc8be754/sjson.go#L260-L262). Unfortunately, deleting keys does not work when `GOOS=js GOARCH=wasm` and silently fails (fails to find the key) because when building for this platform it uses `gjson_gae.go` as per the build tag:

```
//+build appengine js
```

which has a no-op implementation for `fillIndex` which is critical for `sjson`. Copy/pasting the function implementation from `gjson_ngae.go` works correctly. Please can you update the build tags to remove `js`, as the `ngae` version works just fine on WASM. Thanks.

References:

https://github.com/tidwall/gjson/blob/1ed2249f74b3f06f3f84d6c4a781e29f0a93bdc6/gjson_gae.go#L8-L10

**Comment by Kegsay** [comment]
Test case:
```go
package m_test

import (
	"testing"

	"github.com/tidwall/sjson"
)

func TestDeleteJSONWASM(t *testing.T) {
	inputJSON := []byte(`{
		"key1": "a",
		"deleteme": {
			"b": "c"
		}
	}`)

	outputJSON, err := sjson.DeleteBytes(inputJSON, "deleteme")
	if err != nil {
		t.Fatalf("Failed to DeleteBytes: %s", err)
	}
	if len(inputJSON) == len(outputJSON) {
		t.Fatalf("DeleteBytes failed to delete the key")
	}
}
```

Produces:
```
$ go test .                                                                       
ok  	example.com/m	0.204s

$ GOOS=js GOARCH=wasm go test -exec="$(go env GOROOT)/misc/wasm/go_js_wasm_exec" .
--- FAIL: TestDeleteJSONWASM (0.00s)
    main_test.go:22: DeleteBytes failed to delete the key
FAIL
FAIL	example.com/m	0.726s
FAIL
```

**Comment by tidwall** [comment]
I was unaware the the `js` tag is now used by wasm builds. The `js` tag was included because gopherjs uses it, and gopherjs does not support the `unsafe` keyword. Also, Google App Engine (`appengine`) use to not support `unsafe` either, but my understanding is that it now does. 

Based on https://github.com/gopherjs/gopherjs/issues/894, the gopherjs team may be "limiting scope and culling contributions". So I'm not sure about the future of that project. But I predict that wasm will only grow in usage.

I think the best choice is to merge `gjson_ngae.go` into `gjson.go` and delete `gjson_gae.go` and `gjson_ngae.go`. 

I just pushed a new build v1.6.0 that supports wasm.
