### ISSUE TITLE
Why not providing a Get(r io.Reader)

### ISSUE THREAD

**Issue by akhenakh** [tidwall/gjson#17]
The API is forcing translation to the caller

**Comment by tidwall** [comment]
Hi @akhenakh,

The current `gjson.Get(bytes, path)` call does not parse the entire JSON payload. It only parses up to the point that it find the target value and then it immediately returns that value. Thus a `gjson.Get(io.Reader)`, as you suggest, would be problematic because when the value is found the reader will likely be left in an incomplete read position. Also there's no way to rewind an io.Reader, preventing more than one `gjson.Get()` per reader.

In most cases the size of the JSON payload is known prior to parsing so using a utility such `ioutil.ReadAll()` to capture the entire JSON in memory is ideal.

I hope this information is helpful. Let me know if you have any further questions.

Thanks.

**Comment by akhenakh** [comment]
I have a cache in front of my HTTP Gets and then directly feed gjson, so the rewind for a later more parsing was a non issue, but I get your point to keep gjson more generics.
Thanks!

**Comment by mitar** [comment]
Maybe then `io.ReadSeeker` could be required? To be able to seek to the beginning if needed.
