### ISSUE TITLE
Surprising behavior with * wildcard indexing

### ISSUE THREAD

**Issue by JSlote** [tidwall/gjson#178]
Consider

```json
{
  "a": [1],
  "aa": [2,3]
}
```
This is expected:
```
>>> a*.0
1
```
Whereas I'd expect this to return an empty value:
```
>>> a*.1
3
```

It seems like either `a*.1` should return empty OR the wildcard should select _all_ matching fields.

**Comment by tidwall** [comment]
That's by design.

GJSON searches the json for a value at the provided path. As soon as a value is found, it's returned.

In your case "a*.0" is found for both `"a": [1],` and `"aa": [2,3]`, but "a*.1" only found for `"aa": [2,3]`.

This is the case for all gjson paths using the dot syntax, not just ones with a wildcard.

For example:

```json
{
  "person": {"first": "Sara"},
  "person": {"first": "Dale", "age": 37}
}
```

```
>>> person.first
"Sara"

>>> person.age
37
```

An alternative approach is to use the pipe delimiter after your wildcard, which breaks up a single path into smaller paths performing individual queries on each.

```
>>> a*|0
1
```

This basically says, "take the result of `a*` then search for `0` from that result". 

Effectively something like:

```go
gjson.Get(json, "a*").Get("0")
```

And then `a*|1` would then be an empty value.

**Comment by JSlote** [comment]
I see, thanks so much @tidwall for the thorough explanation.
