### ISSUE TITLE
Exclude array within another array

### ISSUE THREAD

**Issue by intbl** [tidwall/gjson#208]
Hi,
I'm using your awesome library in the context of Telegraf and got a question about the depth of parsing.
Array looks like (shortened version only)
{ "scheduler": {
    "schedulerInfo": {
      "queues": {
        "queue": [
          {
            "usedCapacity": 0,
            "numApplications": 0,
            "state": "RUNNING",
            "queues": {
              "queue": [...]
            } } ] } } } }

How can I get everything, except the queues.queue-array on the end?
 
Expected result should be:
[ {
            "usedCapacity": 0,
            "numApplications": 0,
            "state": "RUNNING"
 } ]
The path so far: scheduler.schedulerInfo.queues.queue, which obviously brings everything, also the last array.

I can't do something like 
scheduler.schedulerInfo.queues.queue.usedCapacity,scheduler.schedulerInfo.queues.queue.numApplications, as there are too many paths I would have to enter manually.

Thanks in advance.

**Comment by tidwall** [comment]
```
scheduler.schedulerInfo.queues.queue|#.{usedCapacity,numApplications,state}
```

**Comment by intbl** [comment]
Thanks Josh, issue is, that there is not only {usedCapacity,numApplications,state}, but couple of 100 objects and even arrays of interests. The only not relevant array is queues.queue.
So there is no chance to skip/ignore/drop only queues.queue, without putting all the relevant fields into the path?

**Comment by tidwall** [comment]
```
scheduler.schedulerInfo.queues.queue|#.{usedCapacity,numApplications,state}
```

is composed of a few different things.

First the entire queue is taken using:

```
scheduler.schedulerInfo.queues.queue
```

The pipe `|` character is used instead of a dot `.`, because we need to extract the result of the first path prior to querying the array using `#'. [Dot vs Pipe](https://github.com/tidwall/gjson/blob/master/SYNTAX.md#dot-vs-pipe).

Then we use the `#.` to iterate over all the items in the array. [Arrays](https://github.com/tidwall/gjson/blob/master/SYNTAX.md#arrays)

Finally we use a [Multipath](https://github.com/tidwall/gjson/blob/master/SYNTAX.md#multipath) syntax to generate a new object and allowing for use to cherry-pick the specific members.

```
{usedCapacity,numApplications,state}
```

I used the tool at https://gjson.dev to help me build this path.

**Comment by tidwall** [comment]
> So there is no chance to skip/ignore/drop only queues.queue, without putting all the relevant fields into the path?

No, unfortunately there isn't. But that would pretty cool if it did.

**Comment by intbl** [comment]
Thanks Josh, your code behind the pipe is already very helpful, and will be used in another part of my path.
Will go ahead with adding the required fields of interests, luckily the json structure is not changing this often.

And yepp, some kind of skipping a certain part of a result might be helpful for others as well.
