### ISSUE TITLE
Add support for io.Reader

### ISSUE THREAD

**Issue by emersion** [tidwall/gjson#25]
Add a `Read(io.Reader)` function.

**Comment by tidwall** [comment]
Hi @emersion. Are you thinking as an addition to the Unmarshal or Get function?

**Comment by emersion** [comment]
Nom, that would be a new function, `Read`, that accepts an `io.Reader`.

**Comment by tidwall** [comment]
Then I'm assuming that `Read(io.Reader)` would return a `gjson.Result`, which represents a JSON payload? And subsequent calls to `Read` would return the next JSON payloads in the stream?

**Comment by emersion** [comment]
Yeah, that would be a solution.

**Comment by tidwall** [comment]
Thanks a ton for your suggestion but I’ve decided that it’s best to hold off on this feature for now.

**Comment by emersion** [comment]
Please either explain why you don't want this feature or keep this issue opened.

**Comment by tidwall** [comment]
The `iotuil.ReadAll()` for the JSON payload followed by `gjson.Get()` seems to be the standard process that people are using. I'm not certain for the use case for adding an additional interface.

**Comment by emersion** [comment]
ioutil.ReadAll is not efficient when decoding JSON. By accepting a Reader you allow the payload to be decoded at the same time as it is received, not after. It's better for memory usage too: with a Reader you only use small chunks, with ReadAll you allocate a huge buffer.

That's why all standard library packages accept io.Reader.

**Comment by tidwall** [comment]
I agree that a Reader could be better for memory usage. Could you provide some examples of how you would use the Reader in GJSON?

**Comment by tidwall** [comment]
The only way I'm currently imagining it being used is something like:

```go
result, err := gjson.Read(rd)
if err != nil{
    return err
}
firstName := result.Get("name.first").String()
lastName := result.Get("name.last").String()
```
But in this case the `Read()` function will load the payload in it's entirety into `result`. Which to me is the same as loading the JSON with `ioutil.ReadAll()`.

**Comment by emersion** [comment]
This article explains why `ioutil.ReadAll` is not cool: http://jmoiron.net/blog/crossing-streams-a-love-letter-to-ioreader/

If you use `ioutil.ReadAll` to decode a 1MiB JSON document, a `[]byte` buffer of 1MiB will be allocated _before being passed to gjson_.

`Read` would allow you to write idiomatic Go code when reading an HTTP response, or when reading a file:

```go
resp, err := http.Get("http://example.com/")
if err != nil {
  return err
}
defer req.Body.Close()

result, err := gjson.Read(resp.Body)
if err != nil {
  return err
}
```

`Read` would allow you to parse a stream of JSON messages (not possible with the current implementation):

```go
conn, err := net.Dial("tcp", "golang.org:80")
if err != nil {
  return err
}

for {
  result, err := gjson.Read(conn)
  if err == io.EOF {
    break
  } else if err != nil {
    return err
  }

  // Do something with result
}
```

**Comment by tidwall** [comment]
> This article explains why ioutil.ReadAll is not cool: http://jmoiron.net/blog/crossing-streams-a-love-letter-to-ioreader/

Thanks for sharing the article. It has some interesting points and I agree with most of it. The thing with `ioutil.ReadAll` is that it does one thing very well, reading all the data into a memory. And what GJSON does very well is read values from in-memory JSON payloads. The two work pretty well together. 

To avoid `ioutil.ReadAll` one could know the current size of the payload beforehand and use the `io.ReadFull` instead. This would add a little bit of extra efficiency because the allocation of memory happens once, and avoiding reallocs is always a good thing. But the end result is the same, you have loaded the entire JSON payload into memory.  

> If you use ioutil.ReadAll to decode a 1MiB JSON document, a []byte buffer of 1MiB will be allocated before being passed to gjson.

GJSON only works on an in-memory JSON payload. It's API is designed to work on a `string` or `[]byte`. 

If avoiding loading the JSON completely into memory is main concern, then I suggest using the stdlib `json.Decoder`. It's designed to read tokens one at a time and allows for stream based parsing.

> Read would allow you to parse a stream of JSON messages (not possible with the current implementation)

I agree that it would be pretty cool for multimessage streams. It wouldn't be possible to efficiently read using a `gjson.Read()` function. We would need to create a `gjson.Reader` type, such as:

```go
rd  := gjson.NewReader(resp.Body)
for {
    result, err := rd.Read()
    if err != nil && err != io.EOF {
        return err
    }
    result.Get("name.last")
}

```

**Comment by monerorus** [comment]
For example. I have 1+Gb json stream and it use 2.7Gb RAM for parse. I'm use `ReadAll `and `gjson.GetMany`. But i think if stream would be nested json (json-rpc) it allocate lot of Ram too.

**Comment by mitar** [comment]
I would also love a streaming version of this package, otherwise it is not really possible to extract data from huge (multiple GBs) JSON files without loading everything into the memory. I came to this package thinking this feature is already here as it looks to me like one of the main advantages of parsing JSON first to extract data. Especially with its support for ndjson.
