### ISSUE TITLE
String templating?

### ISSUE THREAD

**Issue by adaml881** [tidwall/gjson#373]
Is there a way to join properties into a single property on the output?

```json
{
  "name": {"first": "Tom", "last": "Anderson"},
  "age":37,
  "children": ["Sara","Alex","Jack"],
  "fav.movie": "Deer Hunter",
  "friends": [
    {"first": "Dale", "last": "Murphy", "age": 44, "nets": ["ig", "fb", "tw"]},
    {"first": "Roger", "last": "Craig", "age": 68, "nets": ["fb", "tw"]},
    {"first": "Jane", "last": "Murphy", "age": 47, "nets": ["ig", "tw"]}
  ]
}
```

Using this example, I'd like to be able to get an output this from the `friends` array

```json
[
   "[first] [last] Aged [age]"
]
```

Example:
```json
[
  "Dale Murphy Aged 44",
  "Roger Craig Aged 68",
  "Jane Murphy Aged 47"
]
```

**Comment by volans-** [comment]
@adaml881 not that I know of, but you could wrote a simple custom modifier ([see docs](https://github.com/tidwall/gjson/blob/master/SYNTAX.md#custom-modifiers)) that joins all the array elements with space and returns a string. Then you could use a query like this one using [multipaths](https://github.com/tidwall/gjson/blob/master/SYNTAX.md#multipaths) to create the array of elemens you want and use your modifier:
```
friends.#.[first,last,!"Aged",age].@spacejoin
```
the above query without the modifier would output:
```json
[["Dale","Murphy","Aged",44],["Roger","Craig","Aged",68],["Jane","Murphy","Aged",47]]
```
Using the  dot instead of the pipe will apply the modifier to each inner array.

**Comment by adaml881** [comment]
Amazing, thank you
