### ISSUE TITLE
Is any way to handle large integer parsing?

### ISSUE THREAD

**Issue by ns-kliu** [tidwall/gjson#375]
As #29 said, gjson is parsing integer to float64
https://github.com/tidwall/gjson/blob/4d230282c0e3bf42fa509147d27d7e8dcc3d3bad/gjson.go#L68-L69

But it's causing a side effect for my use case that accessing by gjson and sjson like this:
```go
	s := `{"id": 3884520826190075694}`
	n := `[]`
	n, _ = sjson.Set(n, "0", gjson.Parse(s).Value())
	fmt.Println(n) // [{"id":3884520826190076000}]
```

Is any way to handle large integer parsing? Really appreciate it.

**Comment by ccoVeille** [comment]
Integer/float is never fun.

Float64 is the type that can fit all others.

But float64 leads to precision errors.

But here, your number fits in an int64

https://go.dev/play/p/GrdWttFHXFl

So, the code behave badly.

You have to consider this architecture logic. A number this big will be sent via the JSON, and someone will read it.

Numbers in JSON are all floats is we refer to the RFC

So, the clients might face the same imprecision with float depending on the clients implementation of the JSON parsing.

While there is a legitimate logic in thinking there is a bug that could be fixed in gjson lib, I would encourage you to reconsider your data structure and use a string to transport such a big number.

**Comment by tidwall** [comment]
By default `Result.Value()` will convert JSON numbers to floats.
Using `Result.Int()` will correctly convert a JSON number to an Int64.

```go
s := `{"id": 3884520826190075694}`
n := `[]`
n, _ = sjson.Set(n, "0.id", gjson.Get(s, "id").Int())
fmt.Println(n) // [{"id": 3884520826190075694}]
```

The way GJSON handles numbers has been a [topic of interest](https://github.com/tidwall/gjson/issues?q=Value+Float64) since the beginning. 

It's been discussed in the past to change Value() to handle numbers differently. #114 #351  
But any change to default behavior will be a breaking change. 

The main thought is to somehow integrate the `UseNumber` technique that is available in the standard `encoding/json` package, but it hasn't been settled as to the best approach.

**Comment by ccoVeille** [comment]
Thanks for providing such good context and explanations

For reference https://pkg.go.dev/encoding/json#Decoder.UseNumber
