### ISSUE TITLE
Add support for io.Reader

### ISSUE THREAD

**Issue by pavelnikolov** [tidwall/gjson#78]
Do you have any plans for supporting an `io.Reader` as json input?
The current implementation looks like this:

```
func Get(json, path string) Result
```

However, I am interested in getting a single value from a large JSON document that I download over the network. I don't want to read the whole document. As soon as I find the value, I would like to return early. Would you consider supporting this:

```
func Get(r io.Reader, path string) Result
```

where the reader above is the JSON input. This would make some of our code more efficient. For example:

### Before:

```
res, err := client.Do(req)
if err != nil {
	// handle err
}

body, err := ioutil.ReadAll(res.Body)
if err != nil {
	// handle err
}
defer res.Body.Close()

val := gjson.Get(string(body), "<some_path>").String()
```

### After:

```
res, err := client.Do(req)
if err != nil {
	// handle err
}
defer res.Body.Close()

val := gjson.Get(res.Body, "<some_path>").String()
```

**Comment by tidwall** [comment]
I don't have plans to add io.Reader for the json input at this time. I absolutely want this feature but the amount of work it would take to do it right is way beyond what I have available.

**Comment by tidwall** [comment]
I've decided that I won't be merging any io.Reader functionality to GJSON until there is a fully flushed out solution. The amount of work to change GJSON to accommodate streaming data over a Reader would require nearly an entire rewrite of the library, which unfortunately I don't have the time for right now.

What I would expect from a GJSON + io.Reader is something like:

```go
res, err := gjson.GetReader(rd, path)
if err != nil {
    return err
}
```

Today the common workaround is:

```go

json, err := ioutil.ReadAll(rd)
if err != nil{
    return err
}
res := gjson.Get(json, path)
```

Which is not ideal because it performs whole-document buffering.


I'm closing this issue for now and also
