### ISSUE TITLE
Parse Errors Being Ignored

### ISSUE THREAD

**Issue by briandowns** [tidwall/gjson#8]
What are your thoughts behind ignoring the errors below?

https://github.com/tidwall/gjson/blob/master/gjson.go#L80
https://github.com/tidwall/gjson/blob/master/gjson.go#L95

https://github.com/tidwall/gjson/blob/master/gjson.go#L323
https://github.com/tidwall/gjson/blob/master/gjson.go#L339
https://github.com/tidwall/gjson/blob/master/gjson.go#L343

https://github.com/tidwall/gjson/blob/master/gjson.go#L846

https://github.com/tidwall/gjson/blob/master/gjson.go#L888

https://github.com/tidwall/gjson/blob/master/gjson.go#L1028

Should these be logged?

**Comment by tidwall** [comment]
This is intentional. We are treating all invalid numbers as zero. The other option is to

```go 
n, err := strconv.ParseFloat(...)
if err != nil{
        n = math.NaN()
}
```

which would be more Javascripty and more accurately describe the value, but NaNs naturally have undefined properties, and don't work as well in sorting and such. 

So for now any invalid number is just treated as zero.

**Comment by briandowns** [comment]
Sounds good. Thanks for the clarification!
